apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polish-history-quest
  namespace: polish-history-quest
  labels:
    app.kubernetes.io/name: polish-history-quest
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: polish-history.k3s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: polish-history-quest
                port:
                  number: 80
