apiVersion: v1
kind: Service
metadata:
  name: polish-history-quest
  namespace: polish-history-quest
  labels:
    app.kubernetes.io/name: polish-history-quest
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: polish-history-quest
  ports:
    - name: http
      port: 80
      targetPort: http
